-- P0-P3 hardening and product features for Le mie medicine.
create schema if not exists private;

-- Usernames are display names, not globally unique identifiers.
do $$
declare constraint_name text;
begin
  select conname into constraint_name from pg_constraint
  where conrelid = 'public.profiles'::regclass and contype = 'u'
    and conkey = array[(select attnum from pg_attribute where attrelid='public.profiles'::regclass and attname='username')];
  if constraint_name is not null then execute format('alter table public.profiles drop constraint %I', constraint_name); end if;
end $$;

alter table public.farmaci
  add column if not exists barcode text,
  add column if not exists soglia_scorta integer not null default 0 check (soglia_scorta >= 0),
  add column if not exists reminder_days integer not null default 30 check (reminder_days between 1 and 365),
  add column if not exists dosaggio text,
  add column if not exists orari text,
  add column if not exists note_mediche text,
  add column if not exists photo_path text,
  add column if not exists updated_at timestamptz not null default now(),
  add column if not exists deleted_at timestamptz;
create index if not exists farmaci_barcode_idx on public.farmaci(barcode) where barcode is not null;
create index if not exists farmaci_active_idx on public.farmaci(user_id, nome) where deleted_at is null;

create table if not exists public.aifa_catalog (
  aic text primary key,
  descrizione text not null,
  principio_attivo text,
  ditta text,
  barcode text,
  updated_at timestamptz not null default now()
);
create unique index if not exists aifa_catalog_barcode_idx on public.aifa_catalog(barcode) where barcode is not null;
alter table public.aifa_catalog enable row level security;
create policy "catalog_read_authenticated" on public.aifa_catalog for select to authenticated using (true);

-- Old per-user cache is retired; keep the empty table temporarily for rollback.
revoke all on public.aifa_cache from anon, authenticated;

create table if not exists public.terapie (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  medicine_id bigint references public.farmaci(id) on delete cascade,
  instruction text not null,
  times text,
  start_date date not null,
  end_date date,
  created_at timestamptz not null default now(),
  check (end_date is null or end_date >= start_date)
);
create index if not exists terapie_user_idx on public.terapie(user_id);
alter table public.terapie enable row level security;
create policy "terapie_owner_all" on public.terapie for all to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

create table if not exists public.caregiver_access (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  caregiver_id uuid not null references auth.users(id) on delete cascade,
  label text,
  created_at timestamptz not null default now(),
  unique(owner_id, caregiver_id),
  check (owner_id <> caregiver_id)
);
create index if not exists caregiver_access_caregiver_idx on public.caregiver_access(caregiver_id);
alter table public.caregiver_access enable row level security;
create policy "shares_read_participants" on public.caregiver_access for select to authenticated
  using ((select auth.uid()) in (owner_id, caregiver_id));
create policy "shares_owner_delete" on public.caregiver_access for delete to authenticated
  using ((select auth.uid()) = owner_id);
create policy "caregiver_read_medicines" on public.farmaci for select to authenticated using (
  exists (select 1 from public.caregiver_access ca where ca.owner_id = farmaci.user_id and ca.caregiver_id = (select auth.uid()))
);
create policy "caregiver_read_treatments" on public.terapie for select to authenticated using (
  exists (select 1 from public.caregiver_access ca where ca.owner_id = terapie.user_id and ca.caregiver_id = (select auth.uid()))
);

create table if not exists public.audit_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  action text not null,
  table_name text not null,
  row_id text,
  created_at timestamptz not null default now()
);
create index if not exists audit_events_user_created_idx on public.audit_events(user_id, created_at desc);
alter table public.audit_events enable row level security;
create policy "audit_read_own" on public.audit_events for select to authenticated using ((select auth.uid()) = user_id);

create or replace function private.audit_row() returns trigger
language plpgsql security definer set search_path = '' as $$
declare payload jsonb; actor uuid;
begin
  payload := case when tg_op = 'DELETE' then to_jsonb(old) else to_jsonb(new) end;
  actor := coalesce(auth.uid(), nullif(payload->>'user_id','')::uuid);
  if actor is not null then
    insert into public.audit_events(user_id, action, table_name, row_id)
    values(actor, lower(tg_op), tg_table_name, payload->>'id');
  end if;
  return coalesce(new, old);
end $$;
revoke all on function private.audit_row() from public, anon, authenticated;
drop trigger if exists audit_farmaci on public.farmaci;
create trigger audit_farmaci after insert or update or delete on public.farmaci for each row execute function private.audit_row();
drop trigger if exists audit_terapie on public.terapie;
create trigger audit_terapie after insert or update or delete on public.terapie for each row execute function private.audit_row();

create or replace function public.invite_caregiver(caregiver_email text, share_label text default null)
returns bigint language plpgsql security definer set search_path = '' as $$
declare target uuid; result_id bigint; owner uuid := auth.uid();
begin
  if owner is null then raise exception 'authentication required'; end if;
  select id into target from auth.users where lower(email)=lower(trim(caregiver_email));
  if target is null or target=owner then raise exception 'invalid caregiver'; end if;
  insert into public.caregiver_access(owner_id, caregiver_id, label)
  values(owner,target,nullif(trim(share_label),''))
  on conflict(owner_id,caregiver_id) do update set label=excluded.label returning id into result_id;
  return result_id;
end $$;
revoke all on function public.invite_caregiver(text,text) from public, anon;
grant execute on function public.invite_caregiver(text,text) to authenticated;

create or replace function public.replace_aifa_catalog(rows jsonb)
returns integer language plpgsql security definer set search_path = '' as $$
declare inserted integer;
begin
  if auth.uid() is null or coalesce(auth.jwt()->'app_metadata'->>'role','') <> 'admin' then raise exception 'admin required'; end if;
  if jsonb_typeof(rows) <> 'array' or jsonb_array_length(rows) > 100000 then raise exception 'invalid catalog'; end if;
  truncate public.aifa_catalog;
  insert into public.aifa_catalog(aic,descrizione,principio_attivo,ditta,barcode)
  select x.aic,x.descrizione,x.principio_attivo,x.ditta,x.barcode
  from jsonb_to_recordset(rows) as x(aic text,descrizione text,principio_attivo text,ditta text,barcode text);
  get diagnostics inserted = row_count;
  return inserted;
end $$;
revoke all on function public.replace_aifa_catalog(jsonb) from public, anon;
grant execute on function public.replace_aifa_catalog(jsonb) to authenticated;

create or replace function public.delete_own_account() returns void
language plpgsql security definer set search_path = '' as $$
declare account_id uuid := auth.uid();
begin
  if account_id is null then raise exception 'authentication required'; end if;
  delete from auth.users where id=account_id;
end $$;
revoke all on function public.delete_own_account() from public, anon;
grant execute on function public.delete_own_account() to authenticated;

create or replace function public.handle_new_user() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  insert into public.profiles(id,username)
  values(new.id,coalesce(nullif(new.raw_user_meta_data->>'username',''),split_part(new.email,'@',1)))
  on conflict(id) do nothing;
  return new;
end $$;
revoke all on function public.handle_new_user() from public, anon, authenticated;

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('medicine-photos','medicine-photos',false,5000000,array['image/jpeg','image/png','image/webp'])
on conflict(id) do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
do $$ begin
  create policy "photo_read_own" on storage.objects for select to authenticated using (bucket_id='medicine-photos' and (storage.foldername(name))[1]=(select auth.uid())::text);
  create policy "photo_insert_own" on storage.objects for insert to authenticated with check (bucket_id='medicine-photos' and (storage.foldername(name))[1]=(select auth.uid())::text);
  create policy "photo_update_own" on storage.objects for update to authenticated using (bucket_id='medicine-photos' and owner_id=(select auth.uid()::text)) with check (bucket_id='medicine-photos' and owner_id=(select auth.uid()::text));
  create policy "photo_delete_own" on storage.objects for delete to authenticated using (bucket_id='medicine-photos' and owner_id=(select auth.uid()::text));
exception when duplicate_object then null; end $$;

revoke all on public.profiles, public.farmaci, public.aifa_catalog, public.terapie, public.caregiver_access, public.audit_events from anon;
grant select,insert,update on public.profiles to authenticated;
grant select,insert,update,delete on public.farmaci, public.terapie, public.caregiver_access to authenticated;
grant select on public.aifa_catalog, public.audit_events to authenticated;
grant usage,select on all sequences in schema public to authenticated;
